name: aprog
description: >
  aprog_dart is a lightweight developer toolkit for Dart and Flutter that provides
  pretty JSON dumps, ANSI-colored console output, stack trace helpers, and dd-style debugging.
version: 1.1.0
homepage: https://github.com/uaproger/aprog_dart
repository: https://github.com/uaproger/aprog_dart

environment:
  sdk: ^3.10.7

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
